# build.yaml (in repository root)
# The comments and header from the template are often the cause of errors.
# Ensure your file looks exactly like this, or that all comments are properly
# indented and do not interfere with the YAML structure.

---
include:
  - board: nice_nano_v2
    shield: spacemousemacropad
    artifact-name: spacemousemacropad_firmware
